name: server-test
on:
  push:
    branches:
      - "*"
    tags:
      - "!*"
    paths:
      - ./server/**
  pull_request:
    branches:
      - "*"
    tags:
      - "!*"
    paths:
      - ./server/**

jobs:
  github-context:
    name: context
    runs-on: ubuntu-latest
    steps:
      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
  test:
    name: test
    working-directory: ./server
    runs-on: ubuntu-latest
    container:
      image: golang:1.13
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: test
        run: make ci-test
      - uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

